"""create disease history

Revision ID: 359acfeb0ff7
Revises: 0dd927afd076
Create Date: 2026-08-02 19:29:18.391051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '359acfeb0ff7'
down_revision: Union[str, Sequence[str], None] = '0dd927afd076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.drop_table('chat_history')
    op.add_column('crop_recommendations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('crop_recommendations', sa.Column('soil_type', sa.String(length=50), nullable=False))
    op.add_column('crop_recommendations', sa.Column('land_area', sa.String(length=50), nullable=False))
    op.add_column('crop_recommendations', sa.Column('season', sa.String(length=50), nullable=False))
    op.add_column('crop_recommendations', sa.Column('location', sa.String(length=100), nullable=False))
    op.add_column('crop_recommendations', sa.Column('recommended_crop', sa.String(length=100), nullable=False))
    op.add_column('crop_recommendations', sa.Column('reason', sa.String(length=255), nullable=False))
    op.add_column('crop_recommendations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_crop_recommendations_id'), 'crop_recommendations', ['id'], unique=False)
    op.create_foreign_key(None, 'crop_recommendations', 'users', ['user_id'], ['id'])
    op.drop_column('crop_recommendations', 'crop_name')
    op.drop_column('crop_recommendations', 'recommendation')
    op.add_column('disease_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('disease_history', sa.Column('image_url', sa.String(length=255), nullable=False))
    op.add_column('disease_history', sa.Column('disease_name', sa.String(length=100), nullable=False))
    op.add_column('disease_history', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('disease_history', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('disease_history', 'treatment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_disease_history_id'), 'disease_history', ['id'], unique=False)
    op.create_index(op.f('ix_disease_history_user_id'), 'disease_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'disease_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('disease_history', 'image')
    op.drop_column('disease_history', 'disease')
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'filename')
    op.add_column('farmer_profiles', sa.Column('village', sa.String(length=100), nullable=False))
    op.add_column('farmer_profiles', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('farmer_profiles', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('farmer_profiles', sa.Column('land_area', sa.String(length=50), nullable=False))
    op.add_column('farmer_profiles', sa.Column('soil_type', sa.String(length=50), nullable=False))
    op.add_column('farmer_profiles', sa.Column('main_crop', sa.String(length=100), nullable=False))
    op.add_column('farmer_profiles', sa.Column('irrigation_type', sa.String(length=100), nullable=False))
    op.add_column('farmer_profiles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_farmer_profiles_id'), 'farmer_profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'farmer_profiles', ['user_id'])
    op.create_foreign_key(None, 'farmer_profiles', 'users', ['user_id'], ['id'])
    op.drop_column('farmer_profiles', 'phone')
    op.drop_column('farmer_profiles', 'location')
    op.drop_column('farmer_profiles', 'name')
    op.add_column('government_schemes', sa.Column('eligibility', sa.Text(), nullable=False))
    op.add_column('government_schemes', sa.Column('benefits', sa.Text(), nullable=False))
    op.add_column('government_schemes', sa.Column('documents_required', sa.Text(), nullable=False))
    op.add_column('government_schemes', sa.Column('official_link', sa.String(length=500), nullable=True))
    op.add_column('government_schemes', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('government_schemes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('government_schemes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_government_schemes_id'), 'government_schemes', ['id'], unique=False)
    op.add_column('market_prices', sa.Column('market_name', sa.String(length=100), nullable=False))
    op.add_column('market_prices', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('market_prices', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('market_prices', sa.Column('minimum_price', sa.Float(), nullable=False))
    op.add_column('market_prices', sa.Column('maximum_price', sa.Float(), nullable=False))
    op.add_column('market_prices', sa.Column('modal_price', sa.Float(), nullable=False))
    op.add_column('market_prices', sa.Column('arrival_date', sa.String(length=20), nullable=False))
    op.add_column('market_prices', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.drop_column('market_prices', 'price')
    op.add_column('weather_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('weather_history', sa.Column('humidity', sa.Float(), nullable=False))
    op.add_column('weather_history', sa.Column('rainfall', sa.Float(), nullable=False))
    op.add_column('weather_history', sa.Column('weather_condition', sa.String(length=100), nullable=False))
    op.add_column('weather_history', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('weather_history', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_weather_history_id'), 'weather_history', ['id'], unique=False)
    op.create_foreign_key(None, 'weather_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_history', type_='foreignkey')
    op.drop_index(op.f('ix_weather_history_id'), table_name='weather_history')
    op.alter_column('weather_history', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('weather_history', 'created_at')
    op.drop_column('weather_history', 'weather_condition')
    op.drop_column('weather_history', 'rainfall')
    op.drop_column('weather_history', 'humidity')
    op.drop_column('weather_history', 'user_id')
    op.add_column('market_prices', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_column('market_prices', 'created_at')
    op.drop_column('market_prices', 'arrival_date')
    op.drop_column('market_prices', 'modal_price')
    op.drop_column('market_prices', 'maximum_price')
    op.drop_column('market_prices', 'minimum_price')
    op.drop_column('market_prices', 'state')
    op.drop_column('market_prices', 'district')
    op.drop_column('market_prices', 'market_name')
    op.drop_index(op.f('ix_government_schemes_id'), table_name='government_schemes')
    op.alter_column('government_schemes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('government_schemes', 'created_at')
    op.drop_column('government_schemes', 'state')
    op.drop_column('government_schemes', 'official_link')
    op.drop_column('government_schemes', 'documents_required')
    op.drop_column('government_schemes', 'benefits')
    op.drop_column('government_schemes', 'eligibility')
    op.add_column('farmer_profiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('farmer_profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('farmer_profiles', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'farmer_profiles', type_='foreignkey')
    op.drop_constraint(None, 'farmer_profiles', type_='unique')
    op.drop_index(op.f('ix_farmer_profiles_id'), table_name='farmer_profiles')
    op.drop_column('farmer_profiles', 'created_at')
    op.drop_column('farmer_profiles', 'irrigation_type')
    op.drop_column('farmer_profiles', 'main_crop')
    op.drop_column('farmer_profiles', 'soil_type')
    op.drop_column('farmer_profiles', 'land_area')
    op.drop_column('farmer_profiles', 'state')
    op.drop_column('farmer_profiles', 'district')
    op.drop_column('farmer_profiles', 'village')
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_name')
    op.add_column('disease_history', sa.Column('disease', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('disease_history', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'disease_history', type_='foreignkey')
    op.drop_index(op.f('ix_disease_history_user_id'), table_name='disease_history')
    op.drop_index(op.f('ix_disease_history_id'), table_name='disease_history')
    op.alter_column('disease_history', 'treatment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('disease_history', 'created_at')
    op.drop_column('disease_history', 'description')
    op.drop_column('disease_history', 'disease_name')
    op.drop_column('disease_history', 'image_url')
    op.drop_column('disease_history', 'user_id')
    op.add_column('crop_recommendations', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('crop_recommendations', sa.Column('crop_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'crop_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_crop_recommendations_id'), table_name='crop_recommendations')
    op.drop_column('crop_recommendations', 'created_at')
    op.drop_column('crop_recommendations', 'reason')
    op.drop_column('crop_recommendations', 'recommended_crop')
    op.drop_column('crop_recommendations', 'location')
    op.drop_column('crop_recommendations', 'season')
    op.drop_column('crop_recommendations', 'land_area')
    op.drop_column('crop_recommendations', 'soil_type')
    op.drop_column('crop_recommendations', 'user_id')
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
