"""create crop recommendation table

Revision ID: d61856694fa7
Revises: 98a76e96e141
Create Date: 2026-07-30 09:29:51.125815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd61856694fa7'
down_revision: Union[str, Sequence[str], None] = '98a76e96e141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.Column('land_area', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('recommended_crop', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_recommendations_id'), 'crop_recommendations', ['id'], unique=False)
    op.alter_column('disease_history', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('disease_history', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('disease_history', 'treatment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('disease_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_disease_history_id'), 'disease_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_history_id'), table_name='disease_history')
    op.alter_column('disease_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('disease_history', 'treatment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('disease_history', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('disease_history', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_crop_recommendations_id'), table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    # ### end Alembic commands ###
