import os
from datetime import datetime

from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)


def generate_pdf(history, current_user):

    # -----------------------------
    # Create Reports Folder
    # -----------------------------
    os.makedirs(
        "uploads/reports",
        exist_ok=True
    )

    pdf_path = f"uploads/reports/report_{history.id}.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # -----------------------------
    # Title
    # -----------------------------
    story.append(
        Paragraph(
            "<b><font size='22'>🌾 Kisan AI</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<b>Disease Detection Report</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Farmer Details
    # -----------------------------
    story.append(
        Paragraph(
            f"<b>Farmer Name :</b> {current_user.full_name}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Email :</b> {current_user.email}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date :</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 15))

    # -----------------------------
    # Uploaded Image
    # -----------------------------
    if history.image_url and os.path.exists(history.image_url):

        story.append(
            Paragraph(
                "<b>Uploaded Crop Image</b>",
                styles["Heading3"]
            )
        )

        story.append(
            Image(
                history.image_url,
                width=3 * inch,
                height=3 * inch
            )
        )

        story.append(Spacer(1, 20))

    # -----------------------------
    # Confidence Formatting
    # -----------------------------
    confidence = history.confidence

    try:
        confidence = f"{float(confidence) * 100:.2f}%"
    except Exception:
        pass

    # -----------------------------
    # Disease Details
    # -----------------------------
    story.append(
        Paragraph(
            f"<b>Category :</b> {history.category}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Disease :</b> {history.disease_name}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence :</b> {confidence}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "<b>Description</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            history.description,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "<b>Treatment</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            history.treatment,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    story.append(
        Paragraph(
            "<b>Prevention</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            history.prevention,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>Generated by Kisan AI 🌾</b>",
            styles["Heading2"]
        )
    )

    # -----------------------------
    # Save PDF
    # -----------------------------
    doc.build(story)

    return pdf_path