import os
from datetime import datetime
from html import escape

from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)


def clean_text(value):
    if value is None:
        return ""
    return escape(str(value))


def format_confidence(value):

    if value is None:
        return "Unknown"

    value = str(value).strip()

    if value.endswith("%"):
        return value

    try:
        number = float(value)

        if number <= 1:
            return f"{number * 100:.2f}%"

        return f"{number:.2f}%"

    except Exception:
        return value


def generate_pdf(history, current_user):

    reports_directory = "uploads/reports"

    os.makedirs(
        reports_directory,
        exist_ok=True
    )

    pdf_path = os.path.join(
        reports_directory,
        f"report_{history.id}.pdf"
    )

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # Title
    story.append(
        Paragraph(
            "<b><font size='22'>Kisan AI</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<b>Disease Detection Report</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))

    # Farmer Details
    story.append(
        Paragraph(
            f"<b>Farmer Name:</b> {clean_text(current_user.full_name)}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Email:</b> {clean_text(current_user.email)}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 15))

    # Uploaded Image
    if history.image_url and os.path.exists(history.image_url):

        try:
            story.append(
                Paragraph(
                    "<b>Uploaded Crop Image</b>",
                    styles["Heading3"]
                )
            )

            story.append(
                Image(
                    history.image_url,
                    width=3 * inch,
                    height=3 * inch
                )
            )

            story.append(
                Spacer(1, 20)
            )

        except Exception as error:

            print(
                f"PDF image error: {error}"
            )

    # Confidence
    confidence = format_confidence(
        history.confidence
    )

    # Disease Details
    story.append(
        Paragraph(
            f"<b>Category:</b> {clean_text(history.category)}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Disease:</b> {clean_text(history.disease_name)}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # Description
    story.append(
        Paragraph(
            "<b>Description</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            clean_text(history.description),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # Treatment
    story.append(
        Paragraph(
            "<b>Treatment</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            clean_text(history.treatment),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 10))

    # Prevention
    story.append(
        Paragraph(
            "<b>Prevention</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            clean_text(history.prevention),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>Generated by Kisan AI</b>",
            styles["Heading2"]
        )
    )

    doc.build(story)

    return pdf_path 